import type { StaffShift } from '@/types';

export const MOCK_STAFF_CONTEXT = {
  currentStaffId: 'STF-001',
  name: 'Nguyễn Văn An',
  role: 'operator',
  assignedParkingId: 'ST001',
  assignedParkingName: 'Trạm Quận 1 - Vincom',
  currentShift: {
    id: 'SHIFT-001',
    staffId: 'STF-001',
    parkingId: 'ST001',
    type: 'morning',
    start: '06:00',
    end: '14:00',
    date: new Date().toISOString().split('T')[0],
    clockedInAt: new Date(new Date().setHours(5, 55, 0, 0)).toISOString(),
  } as StaffShift,
  isClockedIn: true,
};

export const MOCK_PARKING_SLOTS = [
  {
    id: 'SLOT-A1',
    zone: 'A',
    number: 1,
    hasCharger: true,
    chargerId: 'CHG-001',
    status: 'available',
  },
  {
    id: 'SLOT-A2',
    zone: 'A',
    number: 2,
    hasCharger: true,
    chargerId: 'CHG-002',
    status: 'charging',
    vehiclePlate: '51F-123.45',
  },
  {
    id: 'SLOT-A3',
    zone: 'A',
    number: 3,
    hasCharger: true,
    chargerId: 'CHG-003',
    status: 'charging',
    vehiclePlate: '30G-999.99',
  },
  {
    id: 'SLOT-A4',
    zone: 'A',
    number: 4,
    hasCharger: true,
    chargerId: 'CHG-004',
    status: 'reserved',
    vehiclePlate: '51H-567.89',
  },
  { id: 'SLOT-A5', zone: 'A', number: 5, hasCharger: true, chargerId: 'CHG-005', status: 'fault' },
  { id: 'SLOT-B1', zone: 'B', number: 1, hasCharger: false, status: 'available' },
  {
    id: 'SLOT-B2',
    zone: 'B',
    number: 2,
    hasCharger: false,
    status: 'occupied_no_charge',
    vehiclePlate: '60A-111.22',
  },
  { id: 'SLOT-B3', zone: 'B', number: 3, hasCharger: false, status: 'available' },
  {
    id: 'SLOT-C1',
    zone: 'C',
    number: 1,
    hasCharger: true,
    chargerId: 'CHG-006',
    status: 'available',
  },
  {
    id: 'SLOT-C2',
    zone: 'C',
    number: 2,
    hasCharger: true,
    chargerId: 'CHG-007',
    status: 'available',
  },
] as const;
