import type {
  Station,
  Charger,
  User,
  Alert,
  Transaction,
  ChargingEvent,
  AdminProfile,
  RevenueDataPoint,
  ParkingSlot,
} from '@/types';

// Helper to generate ISO dates
const daysAgo = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const MOCK_STATIONS: Station[] = [
  {
    id: 'ST001',
    name: 'Trạm Quận 1 - Vincom Center',
    address: '72 Lê Thánh Tôn, Bến Nghé, Quận 1, TP.HCM',
    coordinates: { lat: 10.778, lng: 106.7025 },
    totalSlots: 10,
    activeChargers: 8,
    status: 'online',
    loadPercent: 85,
    revenueToday: 1250000,
    revenueMonth: 35000000,
    operatingHours: '06:00 - 22:00',
    managerId: 'USR001',
    ownerId: 'OWN001',
  },
  {
    id: 'ST002',
    name: 'Trạm Quận 2 - Thảo Điền Pearl',
    address: '12 Quốc Hương, Thảo Điền, Quận 2, TP.HCM',
    coordinates: { lat: 10.8015, lng: 106.738 },
    totalSlots: 6,
    activeChargers: 2,
    status: 'online',
    loadPercent: 33,
    revenueToday: 450000,
    revenueMonth: 12000000,
    operatingHours: '24/7',
    managerId: 'USR002',
  },
  {
    id: 'ST003',
    name: 'Trạm Quận 7 - Crescent Mall',
    address: '101 Tôn Dật Tiên, Tân Phú, Quận 7, TP.HCM',
    coordinates: { lat: 10.7295, lng: 106.716 },
    totalSlots: 12,
    activeChargers: 11,
    status: 'online',
    loadPercent: 92,
    revenueToday: 2100000,
    revenueMonth: 58000000,
    operatingHours: '08:00 - 22:00',
    managerId: 'USR001',
    ownerId: 'OWN001',
  },
  {
    id: 'ST004',
    name: 'Trạm Bình Thạnh - Landmark 81',
    address: '720A Điện Biên Phủ, Phường 22, Bình Thạnh, TP.HCM',
    coordinates: { lat: 10.794, lng: 106.7225 },
    totalSlots: 20,
    activeChargers: 0,
    status: 'maintenance',
    loadPercent: 0,
    revenueToday: 0,
    revenueMonth: 85000000,
    operatingHours: '24/7',
    managerId: 'USR003',
  },
  {
    id: 'ST005',
    name: 'Trạm Tân Bình - Pico Plaza',
    address: '20 Cộng Hòa, Phường 12, Tân Bình, TP.HCM',
    coordinates: { lat: 10.801, lng: 106.655 },
    totalSlots: 4,
    activeChargers: 0,
    status: 'offline',
    loadPercent: 0,
    revenueToday: 0,
    revenueMonth: 5000000,
    operatingHours: '06:00 - 20:00',
    managerId: 'USR002',
    ownerId: 'OWN001',
  },
  {
    id: 'ST006',
    name: 'Trạm Phú Nhuận - Center Point',
    address: '106 Nguyễn Văn Trỗi, Phường 8, Phú Nhuận, TP.HCM',
    coordinates: { lat: 10.7965, lng: 106.677 },
    totalSlots: 8,
    activeChargers: 4,
    status: 'online',
    loadPercent: 50,
    revenueToday: 850000,
    revenueMonth: 22000000,
    operatingHours: '24/7',
    managerId: 'USR004',
  },
  {
    id: 'ST007',
    name: 'Trạm Quận 10 - Vạn Hạnh Mall',
    address: '11 Sư Vạn Hạnh, Phường 12, Quận 10, TP.HCM',
    coordinates: { lat: 10.7755, lng: 106.669 },
    totalSlots: 15,
    activeChargers: 12,
    status: 'online',
    loadPercent: 80,
    revenueToday: 1800000,
    revenueMonth: 45000000,
    operatingHours: '09:00 - 22:00',
    managerId: 'USR001',
  },
  {
    id: 'ST008',
    name: 'Trạm Gò Vấp - Emart',
    address: '366 Phan Văn Trị, Phường 5, Gò Vấp, TP.HCM',
    coordinates: { lat: 10.825, lng: 106.688 },
    totalSlots: 6,
    activeChargers: 0,
    status: 'offline',
    loadPercent: 0,
    revenueToday: 0,
    revenueMonth: 15000000,
    operatingHours: '07:30 - 22:30',
    managerId: 'USR003',
  },
];

export const MOCK_CHARGERS: Charger[] = [
  // Trạm 1 (10 slots)
  {
    id: 'CHG-001',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    status: 'charging',
    powerKw: 50,
    connectorType: 'CCS2',
    currentEnergyKwh: 15.4,
    lastHeartbeat: new Date().toISOString(),
    sessionDurationMin: 45,
    currentUserId: 'USR005',
    firmwareVersion: 'v2.3.1',
    installationDate: daysAgo(365),
  },
  {
    id: 'CHG-002',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    status: 'charging',
    powerKw: 50,
    connectorType: 'CCS2',
    currentEnergyKwh: 8.2,
    lastHeartbeat: new Date().toISOString(),
    sessionDurationMin: 20,
    currentUserId: 'USR006',
    firmwareVersion: 'v2.3.1',
    installationDate: daysAgo(365),
  },
  {
    id: 'CHG-003',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    status: 'available',
    powerKw: 22,
    connectorType: 'Type2',
    currentEnergyKwh: 0,
    lastHeartbeat: new Date().toISOString(),
    firmwareVersion: 'v2.3.1',
    installationDate: daysAgo(365),
  },
  {
    id: 'CHG-004',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    status: 'fault',
    powerKw: 150,
    connectorType: 'CCS2',
    currentEnergyKwh: 0,
    lastHeartbeat: daysAgo(1),
    firmwareVersion: 'v2.3.0',
    installationDate: daysAgo(365),
  },

  // Trạm 2
  {
    id: 'CHG-005',
    stationId: 'ST002',
    stationName: 'Trạm Quận 2 - Thảo Điền Pearl',
    status: 'available',
    powerKw: 22,
    connectorType: 'Type2',
    currentEnergyKwh: 0,
    lastHeartbeat: new Date().toISOString(),
    firmwareVersion: 'v2.4.0',
    installationDate: daysAgo(200),
  },
  {
    id: 'CHG-006',
    stationId: 'ST002',
    stationName: 'Trạm Quận 2 - Thảo Điền Pearl',
    status: 'charging',
    powerKw: 50,
    connectorType: 'CCS2',
    currentEnergyKwh: 25.1,
    lastHeartbeat: new Date().toISOString(),
    sessionDurationMin: 60,
    currentUserId: 'USR007',
    firmwareVersion: 'v2.4.0',
    installationDate: daysAgo(200),
  },

  // Trạm 4 (Maintenance)
  {
    id: 'CHG-007',
    stationId: 'ST004',
    stationName: 'Trạm Bình Thạnh - Landmark 81',
    status: 'offline',
    powerKw: 150,
    connectorType: 'CCS2',
    currentEnergyKwh: 0,
    lastHeartbeat: daysAgo(2),
    firmwareVersion: 'v2.3.1',
    installationDate: daysAgo(100),
  },
  {
    id: 'CHG-008',
    stationId: 'ST004',
    stationName: 'Trạm Bình Thạnh - Landmark 81',
    status: 'offline',
    powerKw: 150,
    connectorType: 'CCS2',
    currentEnergyKwh: 0,
    lastHeartbeat: daysAgo(2),
    firmwareVersion: 'v2.3.1',
    installationDate: daysAgo(100),
  },

  // Add more as needed to reach 30...
];

export const MOCK_USERS: User[] = [
  {
    id: 'USR001',
    name: 'Nguyễn Văn A',
    email: 'nva@example.com',
    phone: '+84 90 123 4567',
    walletBalance: 500000,
    totalSessions: 45,
    totalKwh: 850.5,
    totalSpent: 4250000,
    status: 'active',
    role: 'owner',
    createdAt: daysAgo(400),
    lastLoginAt: daysAgo(1),
  },
  {
    id: 'USR002',
    name: 'Trần Thị B',
    email: 'ttb@example.com',
    phone: '+84 91 234 5678',
    walletBalance: 15000,
    totalSessions: 12,
    totalKwh: 210.2,
    totalSpent: 1050000,
    status: 'active',
    role: 'user',
    createdAt: daysAgo(150),
    lastLoginAt: daysAgo(5),
  },
  {
    id: 'USR003',
    name: 'Lê Hoàng C',
    email: 'lhc@example.com',
    phone: '+84 92 345 6789',
    walletBalance: 0,
    totalSessions: 5,
    totalKwh: 80.0,
    totalSpent: 400000,
    status: 'suspended',
    role: 'user',
    createdAt: daysAgo(300),
    lastLoginAt: daysAgo(30),
  },
  // Add more as needed to reach 20...
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'ALT001',
    type: 'charger_fault',
    severity: 'critical',
    deviceId: 'CHG-004',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    message: 'Lỗi phần cứng - Quá nhiệt',
    timestamp: daysAgo(0.5),
    resolved: false,
  },
  {
    id: 'ALT002',
    type: 'offline_station',
    severity: 'critical',
    deviceId: 'ST005',
    stationId: 'ST005',
    stationName: 'Trạm Tân Bình - Pico Plaza',
    message: 'Mất kết nối mạng',
    timestamp: daysAgo(1.2),
    resolved: false,
  },
  {
    id: 'ALT003',
    type: 'high_load',
    severity: 'warning',
    deviceId: 'ST003',
    stationId: 'ST003',
    stationName: 'Trạm Quận 7 - Crescent Mall',
    message: 'Tải hệ thống đạt 92%',
    timestamp: daysAgo(0.1),
    resolved: false,
  },
  {
    id: 'ALT004',
    type: 'payment_failed',
    severity: 'info',
    deviceId: 'CHG-001',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    message: 'Giao dịch thất bại do số dư không đủ',
    timestamp: daysAgo(2),
    resolved: true,
    resolvedAt: daysAgo(1.9),
    resolvedBy: 'Admin',
  },
  // Add more...
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'TX001',
    userId: 'USR002',
    userName: 'Trần Thị B',
    chargerId: 'CHG-001',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    startTime: daysAgo(1.1),
    endTime: daysAgo(1.0),
    durationMin: 60,
    energyKwh: 35.5,
    amount: 177500,
    status: 'completed',
  },
  {
    id: 'TX002',
    userId: 'USR003',
    userName: 'Lê Hoàng C',
    chargerId: 'CHG-005',
    stationId: 'ST002',
    stationName: 'Trạm Quận 2 - Thảo Điền Pearl',
    startTime: daysAgo(2.1),
    endTime: daysAgo(2.0),
    durationMin: 45,
    energyKwh: 20.0,
    amount: 100000,
    status: 'completed',
  },
  {
    id: 'TX003',
    userId: 'USR005',
    userName: 'Phạm D',
    chargerId: 'CHG-006',
    stationId: 'ST002',
    stationName: 'Trạm Quận 2 - Thảo Điền Pearl',
    startTime: daysAgo(0.1),
    endTime: '',
    durationMin: 0,
    energyKwh: 5.2,
    amount: 0,
    status: 'pending',
  },
  {
    id: 'TX004',
    userId: 'USR006',
    userName: 'Vũ E',
    chargerId: 'CHG-003',
    stationId: 'ST001',
    stationName: 'Trạm Quận 1 - Vincom Center',
    startTime: daysAgo(5.1),
    endTime: daysAgo(5.05),
    durationMin: 30,
    energyKwh: 15.0,
    amount: 75000,
    status: 'failed',
  },
  // Add more...
];

export const MOCK_ADMIN_PROFILE: AdminProfile = {
  id: 'ADM001',
  name: 'System Admin',
  email: 'admin@evcharge.vn',
  role: 'super_admin',
  lastLoginAt: new Date().toISOString(),
  twoFactorEnabled: true,
};

export const MOCK_REVENUE_DATA: RevenueDataPoint[] = Array.from({ length: 24 }).map((_, i) => ({
  time: new Date(new Date().setHours(i, 0, 0, 0)).toISOString(),
  label: `${i.toString().padStart(2, '0')}:00`,
  revenue: Math.floor(Math.random() * 500000) + 100000,
  energyKwh: Math.floor(Math.random() * 100) + 20,
  sessions: Math.floor(Math.random() * 15) + 2,
}));

export const MOCK_EVENTS: ChargingEvent[] = [
  {
    id: 'EVT001',
    chargerId: 'CHG-001',
    type: 'session_start',
    timestamp: daysAgo(0.5),
    payload: { userId: 'USR002' },
    severity: 'info',
  },
  {
    id: 'EVT002',
    chargerId: 'CHG-004',
    type: 'fault',
    timestamp: daysAgo(1),
    payload: { errorCode: 'E-001', temp: 85 },
    severity: 'critical',
  },
];

export const MOCK_SLOTS: ParkingSlot[] = Array.from({ length: 30 }).map((_, i) => {
  const isReserved = i % 5 === 0;
  const isCharging = i % 4 === 0;
  const isFault = i % 15 === 0;
  const isOccupied = i % 7 === 0;

  let status: ParkingSlot['status'] = 'available';
  if (isFault) status = 'fault';
  else if (isCharging) status = 'charging';
  else if (isReserved) status = 'reserved';
  else if (isOccupied) status = 'occupied_no_charge';

  const parkingIds = ['ST001', 'ST003', 'ST005'] as const;
  const zones = ['A', 'B', 'C'] as const;

  return {
    id: `SLOT-${i + 1}`,
    parkingId: parkingIds[i % 3] as string,
    zone: zones[i % 3] as string,
    number: (i % 10) + 1,
    hasCharger: i % 2 === 0,
    chargerId: i % 2 === 0 ? `CHG-00${(i % 5) + 1}` : undefined,
    status,
    vehiclePlate: status !== 'available' && status !== 'fault' ? `51F-${10000 + i}` : undefined,
    reservedUntil: status === 'reserved' ? new Date(Date.now() + 3600000).toISOString() : undefined,
  };
});
